# Configuracion ruta banner
spring:
  banner:
      location: folderexample/banner.txt
      jpa:
        generate-ddl: true
        hibernate:
          ddl-auto: create
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: root


# Deshabilita mostrar mensaje de error por defecto de spring y muestra el de tomcat
server:
  error:
      whitelabel:
        enabled: false
